### ISSUE TITLE
Missing CHEBIs

### ISSUE THREAD

**Issue by cbizon** [NCATSTranslator/Babel#86]
There seem to be a lot of missing CHEBIs as found through Data Services...
Some examples:

```yaml
babel_tests:
  Resolves:
    - CHEBI:12457
    - CHEBI:86461
    - CHEBI:23770
    - CHEBI:12146
    - CHEBI:1037
    - CHEBI:23649
    - CHEBI:12894
    - CHEBI:572
    - CHEBI:1614
    - CHEBI:9253
    - CHEBI:26504
    - CHEBI:24774
    - CHEBI:76940
    - CHEBI:22051
    - CHEBI:22421
    - CHEBI:714
    - CHEBI:10968
    - CHEBI:3298
    - CHEBI:20232
    - CHEBI:27172
    - CHEBI:74908
    - CHEBI:19659
    - CHEBI:1216
```

There seem to be about 20000 of them.  Spot checking a handful, these seem to be cases where maybe the CHEBI has a structure but doesn't appear in unichem.   This doesn't seem to be a new problem, as it's true in both dev and prod.

----
As of Feb 21, 2026, the following CURIEs don't resolve:

```yaml
babel_tests:
  Resolves:
    - CHEBI:76940
    - CHEBI:22421
    - CHEBI:1216
```
